"""Escape-time computations for the supported fractal families.

Every fractal here is generated by iterating `z -> f(z, c)` from a seed
and counting how many steps it takes for `|z|` to cross an escape radius
(or capping at `max_iter` if it never does — those points are considered
"inside" the set). A continuous ("smooth") iteration count is derived
from the escape step so that colour bands blend instead of banding.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

ESCAPE_RADIUS = 2.0
ESCAPE_RADIUS_SQ = ESCAPE_RADIUS * ESCAPE_RADIUS
_LOG2 = math.log(2.0)


@dataclass(frozen=True)
class Viewport:
    """A rectangular slice of the complex plane to sample, in pixels."""

    width: int
    height: int
    center: complex
    scale: float  # half-height of the viewport, in complex-plane units

    def to_complex(self, px: int, py: int) -> complex:
        aspect = self.width / self.height
        re = self.center.real + (px / self.width - 0.5) * 2 * self.scale * aspect
        im = self.center.imag + (py / self.height - 0.5) * 2 * self.scale
        return complex(re, im)


def _smooth_count(iterations: int, max_iter: int, z: complex) -> float | None:
    """Return a fractional escape count, or None if the point never escaped."""
    if iterations >= max_iter:
        return None
    # Renormalised iteration count (Douady-Hubbard): smooths colour bands.
    log_zmod = math.log(abs(z) ** 2) / 2
    return iterations + 1 - math.log(log_zmod / _LOG2) / _LOG2


def _escape_mandelbrot(c: complex, max_iter: int) -> float | None:
    z = 0j
    for n in range(max_iter):
        z = z * z + c
        if z.real * z.real + z.imag * z.imag > ESCAPE_RADIUS_SQ:
            return _smooth_count(n, max_iter, z)
    return None


def _escape_julia(z: complex, c: complex, max_iter: int) -> float | None:
    for n in range(max_iter):
        z = z * z + c
        if z.real * z.real + z.imag * z.imag > ESCAPE_RADIUS_SQ:
            return _smooth_count(n, max_iter, z)
    return None


def _escape_burning_ship(c: complex, max_iter: int) -> float | None:
    z = 0j
    for n in range(max_iter):
        z = complex(abs(z.real), abs(z.imag))
        z = z * z + c
        if z.real * z.real + z.imag * z.imag > ESCAPE_RADIUS_SQ:
            return _smooth_count(n, max_iter, z)
    return None


def _escape_tricorn(c: complex, max_iter: int) -> float | None:
    z = 0j
    for n in range(max_iter):
        z = z.conjugate() * z.conjugate() + c
        if z.real * z.real + z.imag * z.imag > ESCAPE_RADIUS_SQ:
            return _smooth_count(n, max_iter, z)
    return None


def escape_value(
    fractal: str,
    point: complex,
    max_iter: int,
    julia_c: complex | None = None,
) -> float | None:
    """Dispatch to the right escape-time function for `fractal`.

    `point` is the sampled plane coordinate. For Julia sets it is the
    iteration seed `z0`; for the others it is the iterated constant `c`.
    Returns a smooth escape count, or None for points inside the set.
    """
    if fractal == "mandelbrot":
        return _escape_mandelbrot(point, max_iter)
    if fractal == "julia":
        if julia_c is None:
            raise ValueError("Julia sets require a `julia_c` constant")
        return _escape_julia(point, julia_c, max_iter)
    if fractal == "burningship":
        return _escape_burning_ship(point, max_iter)
    if fractal == "tricorn":
        return _escape_tricorn(point, max_iter)
    raise ValueError(f"Unknown fractal family: {fractal!r}")


FAMILIES = ("mandelbrot", "julia", "burningship", "tricorn")
