"""Generate a self-contained HTML report with interactive charts."""

import json
from datetime import datetime
from typing import Dict, List, Tuple


_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Clauder Report — {repo_name}</title>
<style>
  :root {{
    --bg: #0d1117; --surface: #161b22; --border: #30363d;
    --text: #e6edf3; --muted: #8b949e;
    --green-0: #161b22; --green-1: #0e4429; --green-2: #006d32;
    --green-3: #26a641; --green-4: #39d353;
    --cyan: #58a6ff; --yellow: #e3b341; --red: #f85149;
    --purple: #bc8cff;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; line-height: 1.6; }}
  .wrap {{ max-width: 1100px; margin: 0 auto; padding: 32px 20px; }}
  h1 {{ font-size: 2rem; font-weight: 700; color: var(--cyan); margin-bottom: 4px; }}
  h2 {{ font-size: 1.1rem; font-weight: 600; color: var(--text); margin: 32px 0 16px; border-bottom: 1px solid var(--border); padding-bottom: 8px; }}
  .subtitle {{ color: var(--muted); font-size: 0.9rem; margin-bottom: 32px; }}
  .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 12px; margin-bottom: 32px; }}
  .stat-card {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 16px; }}
  .stat-card .val {{ font-size: 1.7rem; font-weight: 700; color: var(--green-4); }}
  .stat-card .lbl {{ font-size: 0.78rem; color: var(--muted); margin-top: 2px; text-transform: uppercase; letter-spacing: .05em; }}
  /* Heatmap */
  .heatmap-wrap {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 20px; overflow-x: auto; }}
  .heatmap {{ display: inline-grid; grid-template-rows: repeat(7, 13px); grid-auto-flow: column; gap: 3px; }}
  .cell {{ width: 13px; height: 13px; border-radius: 2px; cursor: default; transition: opacity .1s; }}
  .cell:hover {{ opacity: .7; }}
  .c0 {{ background: var(--green-0); border: 1px solid #21262d; }}
  .c1 {{ background: var(--green-1); }}
  .c2 {{ background: var(--green-2); }}
  .c3 {{ background: var(--green-3); }}
  .c4 {{ background: var(--green-4); }}
  .month-labels {{ display: inline-flex; gap: 0; margin-bottom: 4px; }}
  .ml {{ font-size: 11px; color: var(--muted); display: inline-block; }}
  /* Bar charts */
  .bar-chart {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 20px; }}
  .bar-row {{ display: flex; align-items: center; gap: 10px; margin-bottom: 8px; font-size: 0.85rem; }}
  .bar-label {{ width: 200px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; color: var(--muted); flex-shrink: 0; }}
  .bar-track {{ flex: 1; background: #21262d; border-radius: 4px; height: 14px; overflow: hidden; }}
  .bar-fill {{ height: 100%; border-radius: 4px; transition: width .4s ease; }}
  .bar-val {{ width: 80px; text-align: right; color: var(--muted); font-size: 0.8rem; flex-shrink: 0; }}
  /* Timeline */
  .timeline {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 20px; }}
  .commit-row {{ display: flex; gap: 12px; padding: 8px 0; border-bottom: 1px solid #21262d; align-items: baseline; }}
  .commit-row:last-child {{ border-bottom: none; }}
  .commit-hash {{ font-family: monospace; color: var(--cyan); font-size: .8rem; flex-shrink: 0; }}
  .commit-date {{ color: var(--muted); font-size: .8rem; flex-shrink: 0; width: 130px; }}
  .commit-author {{ color: var(--yellow); font-size: .82rem; width: 140px; flex-shrink: 0; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }}
  .commit-msg {{ color: var(--text); font-size: .85rem; flex: 1; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }}
  .commit-stats {{ color: var(--muted); font-size: .75rem; flex-shrink: 0; white-space: nowrap; }}
  .ins {{ color: var(--green-4); }}
  .del {{ color: var(--red); }}
  /* Hour chart */
  .hour-chart {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 20px; }}
  .hour-row {{ display: flex; align-items: center; gap: 10px; margin-bottom: 5px; font-size: 0.8rem; }}
  .hour-lbl {{ width: 45px; color: var(--muted); flex-shrink: 0; }}
  /* Footer */
  footer {{ margin-top: 48px; padding-top: 16px; border-top: 1px solid var(--border); color: var(--muted); font-size: .8rem; text-align: center; }}
  footer a {{ color: var(--cyan); text-decoration: none; }}
</style>
</head>
<body>
<div class="wrap">
  <h1>⚡ {repo_name}</h1>
  <p class="subtitle">Generated by <strong>Clauder — Git Time Machine</strong> on {generated_at}</p>

  <div class="stats-grid">
    {stat_cards}
  </div>

  <h2>📅 Contribution Activity</h2>
  <div class="heatmap-wrap">
    <div class="month-labels" id="month-labels"></div><br>
    <div class="heatmap" id="heatmap"></div>
    <div style="margin-top:10px;display:flex;align-items:center;gap:6px;font-size:11px;color:var(--muted)">
      Less
      <div style="width:13px;height:13px;border-radius:2px;background:var(--green-0);border:1px solid #21262d"></div>
      <div style="width:13px;height:13px;border-radius:2px;background:var(--green-1)"></div>
      <div style="width:13px;height:13px;border-radius:2px;background:var(--green-2)"></div>
      <div style="width:13px;height:13px;border-radius:2px;background:var(--green-3)"></div>
      <div style="width:13px;height:13px;border-radius:2px;background:var(--green-4)"></div>
      More
    </div>
  </div>

  <h2>👥 Contributors</h2>
  <div class="bar-chart" id="author-bars"></div>

  <h2>🔥 File Hotspots</h2>
  <div class="bar-chart" id="hotspot-bars"></div>

  <h2>🕐 Commits by Hour (UTC)</h2>
  <div class="hour-chart" id="hour-chart"></div>

  <h2>📜 Recent Commits</h2>
  <div class="timeline" id="timeline"></div>

  <footer>
    Generated by <a href="https://github.com/kareemrt/clauder">Clauder</a> &mdash; Git Time Machine &bull; {generated_at}
  </footer>
</div>

<script>
const DATA = {data_json};

// ── Heatmap ──────────────────────────────────────────────────────
(function() {{
  const heatmap = document.getElementById('heatmap');
  const mlDiv = document.getElementById('month-labels');
  const today = new Date();
  today.setHours(0,0,0,0);
  const WEEKS = 52;

  // Find start: WEEKS weeks ago, aligned to Monday
  const start = new Date(today);
  start.setDate(start.getDate() - (WEEKS * 7) - ((start.getDay() + 6) % 7));

  const dateMap = DATA.date_map;
  function key(d) {{
    return d.toISOString().slice(0, 10);
  }}
  function heatClass(n) {{
    if (n === 0) return 'c0';
    if (n <= 2)  return 'c1';
    if (n <= 5)  return 'c2';
    if (n <= 10) return 'c3';
    return 'c4';
  }}

  // Build month label map: week column → month abbrev
  let prevMonth = '';
  const monthPositions = [];
  for (let wk = 0; wk <= WEEKS; wk++) {{
    const d = new Date(start);
    d.setDate(d.getDate() + wk * 7);
    const m = d.toLocaleString('default', {{ month: 'short' }});
    if (m !== prevMonth) {{
      monthPositions.push({{ wk, label: m }});
      prevMonth = m;
    }}
  }}

  // Render month labels via absolute positioning wrapper
  mlDiv.style.position = 'relative';
  mlDiv.style.height = '16px';
  mlDiv.style.width = ((WEEKS + 1) * 16) + 'px';
  monthPositions.forEach(({{ wk, label }}) => {{
    const span = document.createElement('span');
    span.textContent = label;
    span.style.position = 'absolute';
    span.style.left = (wk * 16) + 'px';
    span.style.fontSize = '11px';
    span.style.color = 'var(--muted)';
    mlDiv.appendChild(span);
  }});

  // Render cells: grid is row-major (7 rows, col-per-week)
  // CSS grid with grid-auto-flow:column means children are placed column by column
  // So we iterate day-of-week (0=Mon) outer, week inner? No:
  // With grid-template-rows:repeat(7,...) and grid-auto-flow:column, children are placed
  // in column order: first 7 children = col 0 (Mon-Sun), next 7 = col 1, etc.
  for (let wk = 0; wk <= WEEKS; wk++) {{
    for (let dow = 0; dow < 7; dow++) {{
      const d = new Date(start);
      d.setDate(d.getDate() + wk * 7 + dow);
      const cell = document.createElement('div');
      cell.className = 'cell';
      if (d > today) {{
        cell.className += ' c0';
        cell.style.opacity = '0';
      }} else {{
        const k = key(d);
        const n = dateMap[k] || 0;
        cell.className += ' ' + heatClass(n);
        cell.title = k + ': ' + n + ' commit' + (n !== 1 ? 's' : '');
      }}
      heatmap.appendChild(cell);
    }}
  }}
}})();

// ── Author bars ───────────────────────────────────────────────────
(function() {{
  const container = document.getElementById('author-bars');
  const authors = DATA.authors.slice(0, 10);
  const maxC = authors[0] ? authors[0][1].commits : 1;
  const COLORS = ['#58a6ff','#e3b341','#bc8cff','#26a641','#f0883e','#f778ba','#79c0ff'];
  authors.forEach(([name, s], i) => {{
    const pct = (s.commits / DATA.total_commits * 100).toFixed(1);
    const fill = (s.commits / maxC * 100).toFixed(1);
    const row = document.createElement('div');
    row.className = 'bar-row';
    row.innerHTML = `
      <div class="bar-label" title="${{name}}">${{name}}</div>
      <div class="bar-track"><div class="bar-fill" style="width:${{fill}}%;background:${{COLORS[i%COLORS.length]}}"></div></div>
      <div class="bar-val">${{s.commits}} (${{pct}}%)</div>`;
    container.appendChild(row);
  }});
}})();

// ── Hotspot bars ──────────────────────────────────────────────────
(function() {{
  const container = document.getElementById('hotspot-bars');
  const spots = DATA.hotspots;
  const maxC = spots[0] ? spots[0][1] : 1;
  spots.forEach(([path, n]) => {{
    const fill = (n / maxC * 100).toFixed(1);
    const row = document.createElement('div');
    row.className = 'bar-row';
    const short = path.length > 50 ? '…' + path.slice(-49) : path;
    row.innerHTML = `
      <div class="bar-label" title="${{path}}">${{short}}</div>
      <div class="bar-track"><div class="bar-fill" style="width:${{fill}}%;background:#f85149"></div></div>
      <div class="bar-val">${{n}} touches</div>`;
    container.appendChild(row);
  }});
}})();

// ── Hour chart ────────────────────────────────────────────────────
(function() {{
  const container = document.getElementById('hour-chart');
  const maxH = Math.max(...Object.values(DATA.hour_map), 1);
  for (let h = 0; h < 24; h++) {{
    const n = DATA.hour_map[h] || 0;
    const fill = (n / maxH * 100).toFixed(1);
    const row = document.createElement('div');
    row.className = 'hour-row';
    row.innerHTML = `
      <div class="hour-lbl">${{String(h).padStart(2,'0')}}: 00</div>
      <div class="bar-track" style="height:12px"><div class="bar-fill" style="width:${{fill}}%;background:#58a6ff"></div></div>
      <div class="bar-val">${{n}}</div>`;
    container.appendChild(row);
  }}
}})();

// ── Timeline ──────────────────────────────────────────────────────
(function() {{
  const container = document.getElementById('timeline');
  const COLORS = ['#e3b341','#58a6ff','#bc8cff','#26a641','#f0883e'];
  const authorIdx = {{}};
  let ci = 0;
  DATA.commits.slice().reverse().slice(0, 40).forEach(c => {{
    if (!(c.author in authorIdx)) authorIdx[c.author] = ci++ % COLORS.length;
    const acol = COLORS[authorIdx[c.author]];
    const row = document.createElement('div');
    row.className = 'commit-row';
    const ins = c.insertions ? `<span class="ins">+${{c.insertions}}</span>` : '';
    const del = c.deletions  ? `<span class="del">-${{c.deletions}}</span>`  : '';
    row.innerHTML = `
      <span class="commit-date">${{c.date.slice(0,16)}}</span>
      <span class="commit-hash">${{c.hash.slice(0,7)}}</span>
      <span class="commit-author" style="color:${{acol}}" title="${{c.author}}">${{c.author}}</span>
      <span class="commit-msg">${{c.message}}</span>
      <span class="commit-stats">${{ins}} ${{del}}</span>`;
    container.appendChild(row);
  }});
}})();
</script>
</body>
</html>
"""


def _stat_card(label: str, value: str, color: str = "#39d353") -> str:
    return (
        f'<div class="stat-card">'
        f'<div class="val" style="color:{color}">{value}</div>'
        f'<div class="lbl">{label}</div>'
        f'</div>'
    )


def generate_html(
    repo_info: Dict,
    commits,
    author_stats: Dict,
    date_map: Dict[str, int],
    hotspots: List[Tuple[str, int]],
    hour_map: Dict[int, int],
) -> str:
    total = repo_info.get("total_commits", len(commits))
    ins = sum(s["insertions"] for s in author_stats.values())
    dels = sum(s["deletions"] for s in author_stats.values())
    span = (commits[-1].date - commits[0].date).days if len(commits) > 1 else 0

    cards = "".join([
        _stat_card("Total Commits",   f"{total:,}"),
        _stat_card("Contributors",    str(len(author_stats)), "#58a6ff"),
        _stat_card("Lines Added",     f"+{ins:,}",            "#39d353"),
        _stat_card("Lines Removed",   f"−{dels:,}",           "#f85149"),
        _stat_card("Active Days",     f"{span:,}",            "#e3b341"),
        _stat_card("Files Tracked",   str(len(hotspots)),     "#bc8cff"),
    ])

    # Prepare JSON-serialisable data for the browser
    commits_json = [
        {
            "hash":       c.hash,
            "author":     c.author,
            "date":       c.date.isoformat(sep=" "),
            "message":    c.message,
            "insertions": c.insertions,
            "deletions":  c.deletions,
        }
        for c in commits
    ]

    authors_json = sorted(
        [(a, {**s, "first_commit": s["first_commit"].isoformat() if s["first_commit"] else None,
                   "last_commit":  s["last_commit"].isoformat()  if s["last_commit"]  else None})
         for a, s in author_stats.items()],
        key=lambda x: x[1]["commits"],
        reverse=True,
    )

    data = {
        "repo_name":     repo_info.get("name", "repo"),
        "total_commits": total,
        "date_map":      date_map,
        "authors":       authors_json,
        "hotspots":      hotspots,
        "hour_map":      {str(k): v for k, v in hour_map.items()},
        "commits":       commits_json,
    }

    return _HTML.format(
        repo_name=repo_info.get("name", "repo"),
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
        stat_cards=cards,
        data_json=json.dumps(data, default=str),
    )
