"""Export a full Clauder report as a Markdown file."""

from __future__ import annotations

from pathlib import Path

from .git_analyzer import RepoStats


def save_report(
    stats: RepoStats,
    story: str,
    haiku: str,
    tagline: str,
    output_path: str = "clauder_report.md",
) -> str:
    """Write a full Markdown report and return the file path."""
    lines = [
        f"# Clauder Report — {stats.name}",
        "",
        f"> {tagline}",
        "",
        "---",
        "",
        "## Repository at a Glance",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Commits | {stats.total_commits} |",
        f"| Contributors | {len(stats.contributors)} |",
        f"| Lines Added | +{stats.total_insertions:,} |",
        f"| Lines Removed | -{stats.total_deletions:,} |",
        f"| Most Active Day | {stats.most_active_day or 'N/A'} |",
    ]

    if stats.first_commit:
        lines.append(
            f"| Born | {stats.first_commit.date.strftime('%B %d, %Y')} |"
        )
    if stats.last_commit:
        lines.append(
            f"| Latest Commit | {stats.last_commit.date.strftime('%B %d, %Y')} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Contributor Leaderboard",
        "",
    ]
    for i, (name, count) in enumerate(stats.contributors[:10], 1):
        bar = "█" * min(count, 40)
        lines.append(f"{i}. **{name}** — {count} commits `{bar}`")

    lines += [
        "",
        "---",
        "",
        "## Commit Timeline",
        "",
        "```",
    ]
    max_val = max(stats.commits_by_month.values(), default=1)
    for month, count in stats.commits_by_month.items():
        bar_len = int((count / max_val) * 30)
        bar = "█" * bar_len
        lines.append(f"{month}  {bar:30s} {count}")
    lines.append("```")

    lines += [
        "",
        "---",
        "",
        "## Most-Touched Files",
        "",
    ]
    for fp, count in stats.top_files[:8]:
        lines.append(f"- `{fp}` — {count} changes")

    lines += [
        "",
        "---",
        "",
        "## The Story",
        "",
        story,
        "",
        "---",
        "",
        "## Project Haiku",
        "",
        "```",
        haiku,
        "```",
        "",
        "---",
        "",
        "*Generated by [Clauder](https://github.com/kareemrt/clauder) — AI Git Storyteller powered by Claude*",
    ]

    path = Path(output_path)
    path.write_text("\n".join(lines))
    return str(path.resolve())
