"""Classic L-system definitions, ready to expand and render."""

from dataclasses import dataclass

from .core import LSystem


@dataclass(frozen=True)
class Preset:
    description: str
    lsystem: LSystem
    angle: float
    iterations: int
    start_heading: float = 90.0
    draw_chars: str = "FG"


PRESETS: dict[str, Preset] = {
    "koch-snowflake": Preset(
        description="Koch snowflake: a triangle with each edge replaced by a Koch curve.",
        lsystem=LSystem(axiom="F++F++F", rules={"F": "F-F++F-F"}),
        angle=60,
        iterations=4,
        start_heading=0,
    ),
    "koch-island": Preset(
        description="Quadratic Koch island, a square-based variant of the Koch curve.",
        lsystem=LSystem(axiom="F+F+F+F", rules={"F": "F+F-F-FF+F+F-F"}),
        angle=90,
        iterations=3,
        start_heading=0,
    ),
    "sierpinski-triangle": Preset(
        description="Sierpinski triangle traced with a single turtle path.",
        lsystem=LSystem(axiom="F-G-G", rules={"F": "F-G+F+G-F", "G": "GG"}),
        angle=120,
        iterations=6,
        start_heading=0,
    ),
    "dragon-curve": Preset(
        description="Heighway dragon curve, generated by paper-folding rules.",
        lsystem=LSystem(axiom="FX", rules={"X": "X+YF+", "Y": "-FX-Y"}),
        angle=90,
        iterations=11,
        start_heading=0,
    ),
    "fractal-plant": Preset(
        description="Binary-tree-like fractal plant, the canonical L-system example.",
        lsystem=LSystem(
            axiom="X",
            rules={"X": "F+[[X]-X]-F[-FX]+X", "F": "FF"},
        ),
        angle=25,
        iterations=6,
        start_heading=90,
    ),
    "hilbert-curve": Preset(
        description="Hilbert space-filling curve.",
        lsystem=LSystem(
            axiom="A",
            rules={"A": "-BF+AFA+FB-", "B": "+AF-BFB-FA+"},
        ),
        angle=90,
        iterations=5,
        start_heading=0,
    ),
    "gosper-curve": Preset(
        description="Gosper curve (flowsnake), a space-filling curve with hexagonal symmetry.",
        lsystem=LSystem(
            axiom="A",
            rules={
                "A": "A-B--B+A++AA+B-",
                "B": "+A-BB--B-A++A+B",
            },
        ),
        angle=60,
        iterations=4,
        start_heading=0,
        draw_chars="AB",
    ),
}


def get(name: str) -> Preset:
    try:
        return PRESETS[name]
    except KeyError:
        available = ", ".join(sorted(PRESETS))
        raise KeyError(f"unknown preset {name!r}; available presets: {available}") from None
