"""Assemble and render the full GitPulse terminal dashboard."""

from datetime import datetime, timezone

from .charts import (
    RESET, BOLD, DIM, CYAN, GREEN, YELLOW, RED, MAGENTA, GRAY, WHITE,
    sparkline, bar_chart, commit_heatmap, contributor_table, language_bar,
    section_header, BLOCK_FULL,
)


LOGO = rf"""
{CYAN}{BOLD}
   ██████╗ ██╗████████╗██████╗ ██╗   ██╗██╗     ███████╗███████╗
  ██╔════╝ ██║╚══██╔══╝██╔══██╗██║   ██║██║     ██╔════╝██╔════╝
  ██║  ███╗██║   ██║   ██████╔╝██║   ██║██║     ███████╗█████╗
  ██║   ██║██║   ██║   ██╔═══╝ ██║   ██║██║     ╚════██║██╔══╝
  ╚██████╔╝██║   ██║   ██║     ╚██████╔╝███████╗███████║███████╗
   ╚═════╝ ╚═╝   ╚═╝   ╚═╝      ╚═════╝ ╚══════╝╚══════╝╚══════╝
{RESET}{DIM}  Repository Vital Signs Dashboard{RESET}
"""


def _fmt_date(dt):
    return dt.strftime("%Y-%m-%d") if dt else "—"


def _age_str(days):
    if days < 30:
        return f"{days}d"
    if days < 365:
        return f"{days // 30}mo {days % 30}d"
    years = days // 365
    months = (days % 365) // 30
    return f"{years}y {months}mo"


def render(stats: dict) -> str:
    if not stats:
        return f"\n  {RED}No git history found in this directory.{RESET}\n"

    lines = [LOGO]

    # ── Overview ─────────────────────────────────────────────────────────────
    lines.append(section_header("OVERVIEW"))
    repo = stats.get("repo_name", "unknown")
    total = stats["total_commits"]
    age = _age_str(stats["age_days"])
    avg = stats["avg_per_day"]
    streak = stats["streak"]
    added = stats["total_added"]
    removed = stats["total_removed"]
    first = _fmt_date(stats["first_commit"])
    last = _fmt_date(stats["last_commit"])
    n_contrib = len(stats["contributors"])
    recent30 = stats["recent_30_count"]

    lines += [
        f"  {BOLD}{WHITE}Repository{RESET}  {CYAN}{repo}{RESET}",
        f"  {BOLD}{WHITE}Age        {RESET}  {age}   {DIM}({first} → {last}){RESET}",
        f"  {BOLD}{WHITE}Commits    {RESET}  {BOLD}{total:,}{RESET}  "
        f"{DIM}avg {avg}/day · {recent30} in last 30d{RESET}",
        f"  {BOLD}{WHITE}Contributors{RESET} {BOLD}{n_contrib}{RESET}",
        f"  {BOLD}{WHITE}Lines +/-  {RESET}  {GREEN}+{added:,}{RESET} / {RED}-{removed:,}{RESET}",
        f"  {BOLD}{WHITE}Streak     {RESET}  {YELLOW}{'🔥 ' if streak >= 3 else ''}{streak} day{'s' if streak != 1 else ''}{RESET}",
    ]

    # ── Activity (last 30 days sparkline) ────────────────────────────────────
    lines.append(section_header("ACTIVITY  ·  Last 30 Days"))
    daily_vals = list(stats["daily_last30"].values())
    spark = sparkline(daily_vals, width=60)
    days_labels = "  " + DIM + "30d ago" + " " * 46 + "today" + RESET
    lines += [f"  {spark}", days_labels, ""]

    # Weekly bars (last 16 weeks)
    if stats.get("weekly"):
        weekly_display = {k[-3:]: v for k, v in stats["weekly"].items()}  # "W42" style
        lines.append(f"  {BOLD}Weekly commit volume (last 16w){RESET}")
        lines.append(bar_chart(weekly_display, width=30, colour=CYAN, label_width=4, max_bars=16))

    # ── Commit Timing ────────────────────────────────────────────────────────
    lines.append(section_header("COMMIT TIMING"))
    lines.append(commit_heatmap(stats["hour_hist"], stats["weekday_hist"]))

    # ── Contributors ─────────────────────────────────────────────────────────
    lines.append(section_header("CONTRIBUTORS"))
    lines.append(contributor_table(stats["contributors"], max_rows=10))

    # ── Hot Files ────────────────────────────────────────────────────────────
    lines.append(section_header("HOT FILES  ·  Most Touched"))
    if stats["top_churn"]:
        churn_dict = {
            fname.split("/")[-1][:30]: info["touches"]
            for fname, info in stats["top_churn"]
        }
        lines.append(bar_chart(churn_dict, width=35, colour=MAGENTA, label_width=30, max_bars=10))
    else:
        lines.append(f"  {DIM}(no numstat data){RESET}")

    # ── Languages ────────────────────────────────────────────────────────────
    if stats.get("languages"):
        lines.append(section_header("LANGUAGES"))
        lines.append(language_bar(stats["languages"], max_langs=8))

    # ── Footer ───────────────────────────────────────────────────────────────
    now_str = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines += [
        "",
        f"  {DIM}Generated by GitPulse · {now_str}{RESET}",
        "",
    ]

    return "\n".join(lines)
