"""Pre-configured fractal views."""
from typing import Any, Dict

PRESETS: Dict[str, Dict[str, Any]] = {
    "mandelbrot_classic": {
        "name": "Mandelbrot — Classic",
        "description": "The iconic full view of the Mandelbrot set, mathematics' most famous object.",
        "type": "mandelbrot",
        "center": (-0.5, 0.0),
        "zoom": 1.5,
        "max_iter": 256,
        "palette": "inferno",
        "cycle": 32.0,
    },
    "mandelbrot_seahorse": {
        "name": "Mandelbrot — Seahorse Valley",
        "description": "Deep zoom into the intricate seahorse valley at the boundary of the set.",
        "type": "mandelbrot",
        "center": (-0.7435669, 0.1314023),
        "zoom": 0.0017,
        "max_iter": 512,
        "palette": "plasma",
        "cycle": 64.0,
    },
    "mandelbrot_elephant": {
        "name": "Mandelbrot — Elephant Valley",
        "description": "Repeating elephant-tusk structures that recur at ever-finer scales.",
        "type": "mandelbrot",
        "center": (0.2812398, 0.0096567),
        "zoom": 0.004,
        "max_iter": 512,
        "palette": "viridis",
        "cycle": 48.0,
    },
    "julia_rabbit": {
        "name": "Julia Set — Douady's Rabbit",
        "description": "Julia set for c = −0.123 + 0.745i, exhibiting threefold rabbit symmetry.",
        "type": "julia",
        "center": (0.0, 0.0),
        "zoom": 1.6,
        "cx": -0.123,
        "cy": 0.745,
        "max_iter": 256,
        "palette": "electric",
        "cycle": 32.0,
    },
    "burning_ship": {
        "name": "Burning Ship",
        "description": "A dramatic cousin of the Mandelbrot set that resembles a ship on fire.",
        "type": "burning_ship",
        "center": (-0.5, -0.5),
        "zoom": 1.3,
        "max_iter": 256,
        "palette": "fire",
        "cycle": 32.0,
    },
    "newton_cubic": {
        "name": "Newton Fractal — z³ = 1",
        "description": "Newton's method finding the three cube roots of unity; colored by root.",
        "type": "newton",
        "center": (0.0, 0.0),
        "zoom": 1.5,
        "max_iter": 64,
        "palette": None,
        "cycle": None,
    },
}
